#!/usr/bin/env bash

APP_BUNDLE_NAME="PRReviewDesk"
APP_DISPLAY_NAME="PR Review Desk"
APP_EXECUTABLE_NAME="PRReviewDeskApp"
APP_BUNDLE_IDENTIFIER="com.developjik.PRReviewDesk"
APP_MARKETING_VERSION="0.1.0"
APP_BUILD_NUMBER="1"
APP_MINIMUM_SYSTEM_VERSION="14.0"
