#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_BINARY="$ROOT_DIR/.build/debug/PRReviewDeskApp"

cd "$ROOT_DIR"

swift build --product PRReviewDeskApp >/dev/null

output_en="$("$APP_BINARY" --ui-smoke --ui-smoke-language en)"
output_ko="$("$APP_BINARY" --ui-smoke --ui-smoke-language ko)"
output_preference_ko="$("$APP_BINARY" --ui-smoke --ui-smoke-language-preference ko)"
output_language_switch="$("$APP_BINARY" --ui-smoke --ui-smoke-language-switch-defaults ko)"
output_ko_sample="$("$APP_BINARY" --ui-smoke-localization ko)"
output_command="$("$APP_BINARY" --ui-smoke-command-interaction)"
output_keyboard="$("$APP_BINARY" --ui-smoke-command-keyboard)"
output_selection_visual="$("$APP_BINARY" --ui-smoke-command-selection-visual)"
output_layout="$("$APP_BINARY" --ui-smoke-layout-contract)"
output_accessibility="$("$APP_BINARY" --ui-smoke-accessibility-contract)"
output_launch_codex="$("$APP_BINARY" --ui-smoke-launch-codex-readiness)"
output="${output_en}"$'\n'"${output_ko}"$'\n'"${output_preference_ko}"$'\n'"${output_language_switch}"$'\n'"${output_ko_sample}"$'\n'"${output_command}"$'\n'"${output_keyboard}"$'\n'"${output_selection_visual}"$'\n'"${output_layout}"$'\n'"${output_accessibility}"
output="${output}"$'\n'"${output_launch_codex}"

required=(
  "ui_smoke=ready"
  "surface=setup-gate"
  "surface=review-workspace"
  "surface=first-run-setup"
  "surface=repository-sidebar"
  "surface=review-inbox"
  "surface=diff-workspace"
  "surface=review-inspector"
  "surface=submit-preview"
  "surface=command-panel"
  "surface=settings-readiness"
  "ui_language=en"
  "ui_language=ko"
  "localized_sample=submit-preview-title:Submit Review Preview"
  "localized_sample=submit-preview-title:리뷰 제출 미리보기"
  "ui_preference_language=ko"
  "preference_localized_sample=submit-preview-title:리뷰 제출 미리보기"
  "language_switch_default=credentialKindDescription:없음"
  "language_switch_default=tokenValidationStatus:확인 안 됨."
  "language_switch_default=codexCLIStatus:확인하지 않음."
  "language_switch_default=codexLoginStatus:확인하지 않음."
  "launch_codex_readiness=ready"
  "localization=Submit Review Preview"
  "localization=Complete setup in Settings"
  "localization=PR Review Desk keeps setup changes in Settings."
  "localization=No matching repositories"
  "render=setup-gate:desktop"
  "render=setup-gate:compact"
  "render=review-workspace:desktop"
  "render=review-workspace:compact"
  "render=first-run-setup:desktop"
  "render=first-run-setup:compact"
  "render=repository-sidebar:desktop"
  "render=review-inbox:desktop"
  "render=diff-workspace:desktop"
  "render=review-inspector:desktop"
  "render=submit-preview:desktop"
  "render=submit-preview:compact"
  "render=command-panel:desktop"
  "render=settings-readiness:desktop"
  "semantic=setup-gate:desktop"
  "semantic=setup-gate:compact"
  "semantic=review-workspace:desktop"
  "semantic=review-workspace:compact"
  "semantic=first-run-setup:desktop"
  "semantic=first-run-setup:desktop:privacy-disclosure"
  "semantic=first-run-setup:compact:privacy-disclosure"
  "semantic=submit-preview:desktop"
  "semantic=command-panel:desktop"
  "interaction=command-panel:filtered=1"
  "interaction=command-panel:selected=select-section-stale"
  "interaction=command-panel:return=select-section-stale"
  "interaction=command-panel-keyboard:selected-section=stale"
  "interaction=command-panel-keyboard:is-presented=false"
  "interaction=command-panel-keyboard:deferred-submit=0"
  "interaction=command-panel-keyboard:escape-is-presented=false"
  "visual=command-panel:selected-row=select-section-stale"
  "layout=review-inbox:top-content-y="
  "layout=repository-sidebar:top-content-y="
  "accessibility=first-run-setup.no-token:rendered-controls=first-run.codex.check,first-run.codex.help,first-run.github.oauth,first-run.github.restore,first-run.privacy.acknowledge"
  "accessibility=first-run-setup.loaded-token:rendered-controls=first-run.codex.check,first-run.codex.help,first-run.github.reload,first-run.github.validate,first-run.privacy.acknowledge"
  "accessibility=submit-preview:rendered-controls=submit-preview.invalid.deselect[enabled],submit-preview.invalid.reveal[enabled],submit-preview.refresh-safety[enabled],submit-preview.regenerate[enabled],submit-preview.submit[disabled]"
  "accessibility=setup-gate:rendered-controls=setup-gate.open-settings"
  "semantic=command-panel:complete-actions="
  "semantic=command-panel:accessibility-hints"
  "accessibility=review-inbox.stale-saved-draft:rendered-controls=review-inbox.pull-request.74"
  "accessibility=review-inbox.empty-draft-ready:rendered-controls=review-inbox.empty.queue-repository"
  "accessibility=command-panel:rendered-controls="
  "command-panel.action.select-section-stale[selected]"
  "command-panel.search"
  "accessibility=settings.loaded-token:rendered-controls=settings.github.delete,settings.github.oauth,settings.github.restore,settings.github.validate"
  "accessibility=review-inbox:rendered-controls=review-inbox.pull-request.74[selected]"
  "accessibility=review-inbox.queue-recovery:rendered-controls="
  "review-inbox.queue.retry[enabled]"
  "review-inbox.queue.remove[enabled]"
)

for needle in "${required[@]}"; do
  if ! grep -Fq "$needle" <<<"$output"; then
    echo "UI smoke manifest missing: $needle" >&2
    echo "$output" >&2
    exit 1
  fi
done

echo "$output"
